-- Flyway baseline placeholder. Real DDLs are generated by JPA in dev profile.
-- For existing schemas, set baseline-on-migrate=true to let Flyway take over.

-- Example index to ensure exists (idempotent per RDBMS if IF NOT EXISTS supported):
-- CREATE INDEX IF NOT EXISTS idx_user_collection_ownerships_user_category ON user_collection_ownerships(user_id, category);
